# Generated by Django 5.2.4 on 2025-07-30 13:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('b', 'Breakfast'), ('l', 'Lunch'), ('d', 'Dinner'), ('s', 'Snacks')], default='s', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_of_food', models.PositiveIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foods.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.meal')),
            ],
            options={
                'unique_together': {('meal', 'food')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='meal',
            field=models.ManyToManyField(through='foods.MealFood', to='foods.food'),
        ),
    ]
