# Generated by Django 5.2.4 on 2025-08-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
