# Generated by Django 5.2.4 on 2025-08-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
