# Generated by Django 5.2.4 on 2025-07-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_groups_appuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
