name: django-app CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  deploy:

    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Downloading Cloud Foundry CLI"
        run: |
          wget -O cf-cli.tgz "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=8.2.0&source=github"
          tar -xvzf cf-cli.tgz
          sudo mv cf /usr/local/bin
      - name: Login to CF
        run: |
          cf login -a https://api.cf.eu12.hana.ondemand.com --sso
          cf push
